// <auto-generated />
using Biodigestor.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biodigestor.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Biodigestor.Server.Models.Temperatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Temperaturas");
                });

            modelBuilder.Entity("Biodigestor.Server.Models.Volume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Volumes");
                });
#pragma warning restore 612, 618
        }
    }
}
